#pragma once

// ALL WM_USER messages are to be declared here *after* 'WM_FIRST_EMULE_USER_MSG'
enum EUserWndMessages
{
	// *) Do *NOT* place any message *before* WM_FIRST_EMULE_USER_MSG !!
	// *) Do *NOT* use any WM_USER messages in the range WM_USER - WM_USER+0x104 !! (AsyncSocketEx)
	UM_FIRST_EMULE_USER_MSG = (WM_USER + 0x110 + 1)

	// Taskbar
	, UM_TASKBARNOTIFIERCLICKED //+2
	, UM_TRAY_ICON_NOTIFY_MESSAGE

	// Web Server
	, WEB_GUI_INTERACTION //+4
	, WEB_CLEAR_COMPLETED
	, WEB_FILE_RENAME
	, WEB_ADDDOWNLOADS
	, WEB_CATPRIO
	, WEB_ADDREMOVEFRIEND

	// VC
	, UM_VERSIONCHECK_RESPONSE //+10

	// ClosableTabCtrl
	, UM_CLOSETAB	//+11
	, UM_QUERYTAB
	, UM_DBLCLICKTAB

	// Colour popup
	, UM_CPN_SELCHANGE //+14
	, UM_CPN_DROPDOWN
	, UM_CPN_CLOSEUP
	, UM_CPN_SELENDOK
	, UM_CPN_SELENDCANCEL

	, UM_MEDIA_INFO_RESULT //+19
	, UM_ITEMSTATECHANGED
	, UM_SPN_SIZED
	, UM_TABMOVED
	, UM_TREEOPTSCTRL_NOTIFY
	, UM_DATA_CHANGED
	, UM_OSCOPEPOSITION
	, UM_DELAYED_EVALUATE
	, UM_ARCHIVESCANDONE

	// UPnP
	, UM_UPNP_RESULT //+28

	// TreeOptionsCtrl
	, WM_TOC_SETFOCUS_TO_CHILD //+29
	, WM_TOC_REPOSITION_CHILD_CONTROL //+30
};