#!/usr/bin/env python3
'''Materialize the final Preview 2 product UI after legacy/product completion gates.'''
from __future__ import annotations

import pathlib
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "srchybrid"
HERE = pathlib.Path(__file__).resolve().parent
TEMPLATES = HERE / "preview2"

VERSION_TEXT = '''//this file is part of eMule Next
//Copyright (C)2026 eMule Next contributors
//GPL v2 or later
#pragma once

// Product metadata only. Never use Preview 2 version values for eD2K/Kad
// protocol negotiation; the upstream v0.72a protocol core remains authoritative.
#define EMULENEXT_VERSION_MAJOR 0
#define EMULENEXT_VERSION_MINOR 2
#define EMULENEXT_VERSION_PATCH 0
#define EMULENEXT_VERSION_STAGE _T("Preview 2")
#define EMULENEXT_VERSION_TEXT _T("0.2.0 Preview 2")
#define EMULENEXT_PRODUCT_TEXT _T("eMule Next 0.2.0 Preview 2")
#define EMULENEXT_PRODUCT_WITH_CORE_TEXT _T("eMule Next 0.2.0 Preview 2 (eMule v0.72a core, x64)")
'''


def find_repo_head() -> str:
    # In a build activation stage the real checkout is normally somewhere
    # above this script. Failure is harmless; identity remains deterministic
    # and Diagnostics reports 'unknown'.
    for candidate in [HERE, *HERE.parents]:
        if not (candidate / ".git").exists():
            continue
        try:
            return subprocess.check_output(
                ["git", "rev-parse", "--short=12", "HEAD"],
                cwd=str(candidate), text=True, stderr=subprocess.DEVNULL,
            ).strip()
        except Exception:
            pass
    return "unknown"


def insert_project_entry(text: str, entry: str, anchors: tuple[str, ...], label: str) -> str:
    if entry in text:
        return text
    for anchor in anchors:
        if anchor in text:
            return text.replace(anchor, anchor + entry, 1)
    raise SystemExit(f"Preview2: {label} project anchor missing")


def patch_project() -> None:
    path = SRC / "emule.vcxproj"
    text = path.read_text(encoding="utf-8-sig", errors="ignore")

    # Prefer stable eMule Next core entries which already exist in the base
    # repository. DB2 maintenance entries are accepted as fallbacks, but the
    # Preview2 product layer no longer depends on their exact placement.
    text = insert_project_entry(
        text,
        '    <ClCompile Include="EmuleNextModernUi.cpp" />\n',
        (
            '    <ClCompile Include="EmuleNextDatabase.cpp" />\n',
            '    <ClCompile Include="EmuleNextDatabaseMaintenance.cpp" />\n',
            '    <ClCompile Include="EmuleNextRuntime.cpp" />\n',
        ),
        "modern UI compile",
    )
    text = insert_project_entry(
        text,
        '    <ClInclude Include="EmuleNextModernUi.h" />\n',
        (
            '    <ClInclude Include="EmuleNextDatabase.h" />\n',
            '    <ClInclude Include="EmuleNextDatabaseMaintenance.h" />\n',
            '    <ClInclude Include="EmuleNextRuntime.h" />\n',
        ),
        "modern UI header",
    )
    text = insert_project_entry(
        text,
        '    <ClInclude Include="EmuleNextBuildIdentity.h" />\n',
        (
            '    <ClInclude Include="EmuleNextModernUi.h" />\n',
            '    <ClInclude Include="EmuleNextDatabase.h" />\n',
        ),
        "build identity header",
    )
    path.write_text(text, encoding="utf-8")


def main() -> int:
    for name in (
        "EmuleNextSettingsWnd.h",
        "EmuleNextSettingsWnd.cpp",
        "EmuleNextDiagnosticsWnd.h",
        "EmuleNextDiagnosticsWnd.cpp",
    ):
        source = TEMPLATES / name
        if not source.exists():
            raise SystemExit(f"Preview2: missing template {name}")
        shutil.copyfile(source, SRC / name)

    (SRC / "EmuleNextVersion.h").write_text(VERSION_TEXT, encoding="ascii")
    head = find_repo_head()
    (SRC / "EmuleNextBuildIdentity.h").write_text(
        "// generated by activate-preview2-core.py\n#pragma once\n"
        f'#define EMULENEXT_BUILD_HEAD _T("{head}")\n',
        encoding="ascii",
    )
    patch_project()

    print(f"eMule Next Preview 2 core materialized (build {head})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
