#!/usr/bin/env python3
'''Materialize the final Preview 2 product UI after legacy/product completion gates.'''
from __future__ import annotations

import pathlib
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "srchybrid"
HERE = pathlib.Path(__file__).resolve().parent
TEMPLATES = HERE / "preview2"

VERSION_TEXT = '''//this file is part of eMule Next
//Copyright (C)2026 eMule Next contributors
//GPL v2 or later
#pragma once

// Product metadata only. Never use Preview 2 version values for eD2K/Kad
// protocol negotiation; the upstream v0.72a protocol core remains authoritative.
#define EMULENEXT_VERSION_MAJOR 0
#define EMULENEXT_VERSION_MINOR 2
#define EMULENEXT_VERSION_PATCH 0
#define EMULENEXT_VERSION_STAGE _T("Preview 2")
#define EMULENEXT_VERSION_TEXT _T("0.2.0 Preview 2")
#define EMULENEXT_PRODUCT_TEXT _T("eMule Next 0.2.0 Preview 2")
#define EMULENEXT_PRODUCT_WITH_CORE_TEXT _T("eMule Next 0.2.0 Preview 2 (eMule v0.72a core, x64)")
'''


def find_repo_head() -> str:
    # In a build activation stage the real checkout is normally four parents
    # above this script. Failure is harmless; product identity still remains
    # deterministic and the UI reports 'unknown'.
    candidates = [HERE, *HERE.parents]
    for candidate in candidates:
        if not (candidate / ".git").exists():
            continue
        try:
            return subprocess.check_output(
                ["git", "rev-parse", "--short=12", "HEAD"],
                cwd=str(candidate), text=True, stderr=subprocess.DEVNULL,
            ).strip()
        except Exception:
            pass
    return "unknown"


def patch_project() -> None:
    path = SRC / "emule.vcxproj"
    text = path.read_text(encoding="utf-8-sig", errors="ignore")
    compile_anchor = '    <ClCompile Include="EmuleNextDatabaseMaintenance.cpp" />\n'
    include_anchor = '    <ClInclude Include="EmuleNextDatabaseMaintenance.h" />\n'
    if '<ClCompile Include="EmuleNextModernUi.cpp" />' not in text:
        if compile_anchor not in text:
            raise SystemExit("Preview2: modern UI compile anchor missing")
        text = text.replace(compile_anchor, compile_anchor + '    <ClCompile Include="EmuleNextModernUi.cpp" />\n', 1)
    if '<ClInclude Include="EmuleNextModernUi.h" />' not in text:
        if include_anchor not in text:
            raise SystemExit("Preview2: modern UI header anchor missing")
        text = text.replace(include_anchor, include_anchor + '    <ClInclude Include="EmuleNextModernUi.h" />\n    <ClInclude Include="EmuleNextBuildIdentity.h" />\n', 1)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    for name in ("EmuleNextSettingsWnd.h", "EmuleNextSettingsWnd.cpp", "EmuleNextDiagnosticsWnd.h", "EmuleNextDiagnosticsWnd.cpp"):
        source = TEMPLATES / name
        if not source.exists():
            raise SystemExit(f"Preview2: missing template {name}")
        shutil.copyfile(source, SRC / name)

    (SRC / "EmuleNextVersion.h").write_text(VERSION_TEXT, encoding="ascii")
    head = find_repo_head()
    (SRC / "EmuleNextBuildIdentity.h").write_text(
        "// generated by activate-preview2-core.py\n#pragma once\n"
        f'#define EMULENEXT_BUILD_HEAD _T("{head}")\n',
        encoding="ascii",
    )
    patch_project()

    print(f"eMule Next Preview 2 core materialized (build {head})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
